// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'column-label'
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menu-clear'
  | 'menu-custom'
  | 'menu-high'
  | 'menu-low'
  | 'menu-medium'
  | 'menu-priority'
  | 'pref-format'
  | 'pref-format-bar'
  | 'pref-format-number'
  | 'pref-format-stars'
  | 'pref-help'
  | 'pref-level-high'
  | 'pref-level-low'
  | 'pref-level-medium'
  | 'pref-levels'
  | 'pref-step'
  | 'pref-title'
  | 'prefs-title'
  | 'prompt-custom-text'
  | 'status-cleared'
  | 'status-set';
