// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "format": string;
      "step": number;
      "levelHigh": number;
      "levelMedium": number;
      "levelLow": number;
      "aiProvider": string;
      "aiModel": string;
      "aiApiKey": string;
      "collectionContexts": string;
    };
  }
}
